// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM_M-D3O1rfvffgdfgdGO74vfuLRKS_txg4Gf5yo',
    appId: '1:409329025378:andfgdroid:8712cc8030e0fgdffb0b9c2c3b',
    messagingSenderId: '409329fdg025378',
    projectId: 'luna-3-7e89fgc',
    storageBucket: 'luna-3-7e8fgfgv9c.firebafsestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtxfgfHdJt1k9aC_ld6q444cgOfgvft0RSU9wFYM',
    appId: '1:409329fgvdf025378:ios:b69a1600bfgvbdf9a6e949c2c3b',
    messagingSenderId: '409329fgvdf025378',
    projectId: 'luna-3-7ef89c',
    storageBucket: 'luna-3-7e8fgvf9c.firebasestorage.app',
    iosBundleId: 'com.exafmple.luna3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtxHdJfbgft1k9aC_ld6q444fgfcgOt0RSU9wFYM',
    appId: '1:40932902fgv5378:ios:b69a16fgvf00b09a6e949c2c3b',
    messagingSenderId: '4093f29025378',
    projectId: 'luna-3-7e89fc',
    storageBucket: 'luna-3-7ef89c.firebasestoragef.app',
    androidClientId: '409329025378-jpd80tln70d1lfbfq286iiv9mb8l5oki9a2.apps.googleusercontent.com',
    iosClientId: '40932bfdxb9025378-7007m8knuietc4dofbdfbjl64sr6t9eq6rilu.apps.googleusercontent.com',
    iosBundleId: 'com.example.lunaf3',
  );

}